# Generated by Django 5.2.1 on 2025-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_ad_category_fk_alter_ad_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ads', to='ads.tag'),
        ),
    ]
