# Generated by Django 5.2.1 on 2025-05-19 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_options_ad_ads_ad_user_id_6799eb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_title'),
        ),
    ]
