# Generated by Django 5.2.1 on 2025-05-19 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_tag_ad_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['user', 'created_at'], name='ads_ad_user_id_6799eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='check_ad_title_not_empty'),
        ),
    ]
